<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Grace</string>
  <key>scopeName</key>
  <string>source.grace</string>
  <key>fileTypes</key>
  <array>
    <string>grace</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.import.grace</string>
      <key>begin</key>
      <string>\b(import)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.import.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>($|;)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#module_name</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.class.grace</string>
      <key>match</key>
      <string>\b(class)\s+([A-z][A-z\d']*)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.class.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.class.grace</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.type.grace</string>
      <key>begin</key>
      <string>\b(type)\s+([A-z][A-z\d']*)\s*(=)\s*\{</string>
      <key>end</key>
      <string>\}</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.type.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.grace</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.type.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-z][A-z\d']*)(?:\s*:\s*([A-z][A-z\d'\s|&amp;]*))?\s*[,\)]</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.method.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.type.method.parameter.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>:\s*([A-z][A-z\d'\s|&amp;]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.field.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(->)\s*([A-z][A-z\d'\s|&amp;]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.type.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.type.method.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>[A-z][A-z\d']*</string>
          <key>name</key>
          <string>entity.name.method.grace</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.method.grace</string>
      <key>begin</key>
      <string>\b(method)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.method.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\{</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([A-z][A-z\d']*)(?:\s*:\s*([A-z][A-z\d'\s|&amp;]*))?\s*[,\)]</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.method.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.type.method.parameter.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(->)\s*([A-z][A-z\d']*)\s*</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.type.method.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.type.method.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-z][A-z\d']*)\s*</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.method.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.begin.grace</string>
          <key>match</key>
          <string>\(</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.definition.parameters.end.grace</string>
          <key>match</key>
          <string>\)</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.definition.grace</string>
      <key>match</key>
      <string>(def|var)\s+([A-z][A-z\d']*)(?:\s*:\s*([A-z][A-z\d'\s|&amp;]*))?</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.definition.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.definition.grace</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>storage.type.definition.grace</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.block.grace</string>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>(-&gt;)|(.(?!-&gt;))*?(?=$|[^A-z\d\s'_,:])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([A-z][A-z\d']*|_)(?:\s*:\s*([A-z][A-z\d'\s|&amp;]*))?</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.block.parameter.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>storage.type.block.parameter.grace</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.grace</string>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>"</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.grace</string>
        </dict>
        <dict>
          <key>name</key>
          <string>source.grace.embedded.source</string>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.embedded.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.section.embedded.grace</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.grace</string>
      <key>match</key>
      <string>\b(return)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.operator.grace</string>
      <key>match</key>
      <string>[|!%$?&amp;\*~+:\-=&lt;/&gt;\\]+</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.grace</string>
      <key>match</key>
      <string>\b(var|def|method|class|type|inherits)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.grace</string>
      <key>match</key>
      <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.object.grace</string>
      <key>match</key>
      <string>\bobject\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>support.method.grace</string>
      <key>match</key>
      <string>\b(if|then|else|elseif|for|while|do|match|case|print)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>variable.language.self.grace</string>
      <key>match</key>
      <string>\b(super|self)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.true.grace</string>
      <key>match</key>
      <string>\btrue\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.false.grace</string>
      <key>match</key>
      <string>\bfalse\b</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comment</key>
    <dict>
      <key>match</key>
      <string>//.*$</string>
      <key>name</key>
      <string>comment.line.grace</string>
    </dict>
    <key>module_name</key>
    <dict>
      <key>match</key>
      <string>[A-Za-z][\w']*</string>
      <key>name</key>
      <string>support.other.module.grace</string>
    </dict>
    <key>declaration_type</key>
    <dict>
      <key>match</key>
      <string>([A-Za-z][\w']*)(\s*:\s*([A-Za-z][\w']*))?</string>
    </dict>
  </dict>
  <key>uuid</key>
  <string>ca03e751-04ef-4330-9a6b-9b99aae1c419</string>
</dict>
</plist>
