<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Grace</string>
  <key>scopeName</key>
  <string>source.grace</string>
  <key>fileTypes</key>
  <array>
    <string>grace</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>name</key>
      <string>comment.line.grace</string>
      <key>match</key>
      <string>//.*$</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.import.grace</string>
      <key>begin</key>
      <string>\b(import)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>($|;)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#module_name</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.class.grace</string>
      <key>match</key>
      <string>\b(class)\s+([A-z_]\w*)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.class.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.class.grace</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.method.grace</string>
      <key>begin</key>
      <string>\b(method)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.method.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\{</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([A-z_]\w*)\s*((\()([^\)]*)(\)))?</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.method.grace</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.begin.grace</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.method.grace</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.parameters.begin.grace</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.block.grace</string>
      <key>match</key>
      <string>\{([\w,\s]+)(-&gt;)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.block.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.grace</string>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.js</string>
        </dict>
      </dict>
      <key>end</key>
      <string>"</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.js</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.grace</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.grace</string>
      <key>match</key>
      <string>\b(return)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.operator.grace</string>
      <key>match</key>
      <string>[|!%$?&amp;\*~+:\-=&lt;/&gt;\\]+</string>
    </dict>
    <dict>
      <key>name</key>
      <string>storage.type.grace</string>
      <key>match</key>
      <string>\b(var|def|method)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.grace</string>
      <key>match</key>
      <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>support.method.grace</string>
      <key>match</key>
      <string>\b(if|then|else|elseif|for|while|do)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.true.grace</string>
      <key>match</key>
      <string>\btrue\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.false.grace</string>
      <key>match</key>
      <string>\bfalse\b</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>module_name</key>
    <dict>
      <key>match</key>
      <string>[A-Za-z]\w*</string>
      <key>name</key>
      <string>support.other.module.grace</string>
    </dict>
  </dict>
  <key>uuid</key>
  <string>ca03e751-04ef-4330-9a6b-9b99aae1c419</string>
</dict>
</plist>
