<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Grace</string>
  <key>scopeName</key>
  <string>source.grace</string>
  <key>fileTypes</key>
  <array>
    <string>grace</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#comma</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.import.grace</string>
      <key>match</key>
      <string>(import)\s*(".*")\s*(as)\s+([A-z][A-z\d']*)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.import.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.path.grace</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>keyword.as.grace</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>entity.identifier.grace</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.type.literal.grace</string>
      <key>begin</key>
      <string>(?:(?&lt;![A-z\d'])(type)|(=))\s*\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.type.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#signature</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.function.grace</string>
          <key>match</key>
          <string>[A-z][A-z\d']*|[-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]*</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.type.grace</string>
      <key>begin</key>
      <string>(?&lt;![A-z\d'])(type)(?![A-z\d'])(?!\s*\{)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.type.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?==)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.type.generic.grace</string>
          <key>begin</key>
          <string>([A-z][A-z\d']*)(&lt;)</string>
          <key>end</key>
          <string>(&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.type.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.type.generic.grace</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#bad_names</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#bad_operators</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#comma</string>
            </dict>
            <dict>
              <key>name</key>
              <string>entity.type.generic.grace</string>
              <key>match</key>
              <string>[A-z][A-z\d']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![A-z\d'])(is)(?![A-z\d'])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?==)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>name</key>
              <string>support.type.annotation.grace</string>
              <key>match</key>
              <string>[A-z][A-z\d']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.type.grace</string>
          <key>match</key>
          <string>[A-z][A-z\d']*</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.method.grace</string>
      <key>begin</key>
      <string>(?&lt;![A-z\d'])(method)(?![A-z\d'])</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=\{)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#signature</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.function.grace</string>
          <key>match</key>
          <string>[A-z][A-z\d']*|[-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]*</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.class.grace</string>
      <key>begin</key>
      <string>\b(class)(?![A-z\d'])</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.class.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=\{)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#signature</string>
        </dict>
        <dict>
          <key>name</key>
          <string>keyword.operator.class.grace</string>
          <key>match</key>
          <string>\.</string>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.name.class.grace</string>
          <key>match</key>
          <string>(?&lt;=class)\s*([A-z][A-z\d']*)\s*(\.)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.class.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.class.grace</string>
          <key>match</key>
          <string>[A-z][A-z\d']*|[-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]*</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.definition.grace</string>
      <key>begin</key>
      <string>(?&lt;![A-z\d'])(def)(?![A-z\d'])</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.definition.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?&lt;![^\w\d'\s])(?:(=)|(:=))(?![^\w\s])|$</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#signature_args</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![A-z\d'])(is)(?![A-z\d'])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=(?&lt;![^\w\d'\s])(?:(=)|(:=))(?![^\w\d'\s]))|$</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>name</key>
              <string>support.type.annotation.grace</string>
              <key>match</key>
              <string>[A-z][A-z\d']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.definition.grace</string>
          <key>match</key>
          <string>\b_\b|[A-z][A-z\d']*</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.variable.grace</string>
      <key>begin</key>
      <string>(?&lt;![A-z\d'])(var)(?![A-z\d'])</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.variable.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?&lt;![^\w\d'\s])(?:(:=)|(=))(?![^\w\d'\s])|$</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![^\w\d'\s\(,])(:)(?![^\w\d'\s\),])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=$|,|\)|(?&lt;=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|^)(:|=|:=|-&gt;)(?=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|$))</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#type</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![A-z\d'])(is)(?![A-z\d'])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=(?&lt;![^\w\d'\s])(?:(=)|(:=))(?![^\w\d'\s]))|$</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>name</key>
              <string>support.type.annotation.grace</string>
              <key>match</key>
              <string>[A-z][A-z\d']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_operators</string>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.variable.grace</string>
          <key>match</key>
          <string>\b_\b|[A-z][A-z\d']*</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.block.grace</string>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.parameters.block.grace</string>
      <key>begin</key>
      <string>(?&lt;=\{)(?=[^{}]*[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\}]-&gt;[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^])</string>
      <key>end</key>
      <string>(-&gt;)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#signature_args</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comma</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#number</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_operators</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[A-z][A-z\d']*</string>
          <key>name</key>
          <string>entity.parameter.grace</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>include</key>
      <string>#string</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#generic</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])(return)(?![A-z\d'])</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.operator.grace</string>
      <key>match</key>
      <string>(?&lt;=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|^)(:|=|:=|\.|-&gt;)(?=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|$)</string>
    </dict>
    <dict>
      <key>name</key>
      <string>support.function.operator.grace</string>
      <key>match</key>
      <string>[-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]*</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])(dialect|import|as|object|method|class|type|def|var|where|is|inherits)(?![A-z\d'])</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#number</string>
    </dict>
    <dict>
      <key>name</key>
      <string>variable.language.self.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])(super|self|outer)(?![A-z\d'])</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.true.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])true(?![A-z\d'])</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.false.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])false(?![A-z\d'])</string>
    </dict>
    <dict>
      <key>name</key>
      <string>support.type.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])[A-Z][A-z\d']*(?![A-z\d']|\s*\.\s*[A-z])</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comment</key>
    <dict>
      <key>match</key>
      <string>//.*$</string>
      <key>name</key>
      <string>comment.line.grace</string>
    </dict>
    <key>comma</key>
    <dict>
      <key>name</key>
      <string>keyword.grace</string>
      <key>match</key>
      <string>,</string>
    </dict>
    <key>number</key>
    <dict>
      <key>name</key>
      <string>constant.numeric.grace</string>
      <key>match</key>
      <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
    </dict>
    <key>string</key>
    <dict>
      <key>name</key>
      <string>string.quoted.double.grace</string>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.grace</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(")|(\n)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.grace</string>
        </dict>
        <dict>
          <key>name</key>
          <string>source.embedded.grace</string>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>keyword.interpolation.begin.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>keyword.interpolation.end.grace</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>bad_names</key>
    <dict>
      <key>name</key>
      <string>invalid.illegal.grace</string>
      <key>match</key>
      <string>(?&lt;![A-z\d'])(dialect|import|as|object|method|class|type|def|var|where|is|inherits|self|super|outer)(?![A-z\d'])</string>
    </dict>
    <key>bad_operators</key>
    <dict>
      <key>name</key>
      <string>invalid.illegal.grace</string>
      <key>match</key>
      <string>[-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]+</string>
    </dict>
    <key>generic</key>
    <dict>
      <key>name</key>
      <string>meta.type.generic.grace</string>
      <key>begin</key>
      <string>(?:([A-Z][A-z\d']*)|[a-z][A-z\d']*)(&lt;)(?![-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^])</string>
      <key>end</key>
      <string>(&gt;)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>support.type.grace</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.operator.grace</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#generic</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
      </array>
    </dict>
    <key>type</key>
    <dict>
      <key>name</key>
      <string>support.type.grace</string>
      <key>match</key>
      <string>[A-z][A-z\d']*(?![A-z\d']|\s*\.\s*[A-z])</string>
    </dict>
    <key>signature_args</key>
    <dict>
      <key>name</key>
      <string>meta.signature.grace</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\*</string>
          <key>name</key>
          <string>keyword.variadic.grace</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![^\w\d'\s\(,])(:)(?![^\w\d'\s\),])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=,|\)|(?&lt;=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|^)(:|=|:=|-&gt;)(?=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|$))</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#type</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>match</key>
          <string>[A-z][A-z\d']*(?=\s*[,\:\)])</string>
          <key>name</key>
          <string>entity.function.grace</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comma</string>
        </dict>
      </array>
    </dict>
    <key>signature</key>
    <dict>
      <key>name</key>
      <string>meta.signature.grace</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|^)(-&gt;)(?=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]|$)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=(?&lt;![A-z\d'])is(?![A-z\d'])|\{|\}|(?&lt;=[A-z\d'"&gt;)])(?&lt;!-&gt;)\s+$)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#type</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.signature.prefix.grace</string>
          <key>match</key>
          <string>(prefix)\s*(?:(:(?:=?)(?=[^-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]))|([-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.grace</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.function.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.signature.assign.grace</string>
          <key>match</key>
          <string>([A-z][A-z0-9']*)\s*(:=)\s*(?=\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.function.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.signature.binary.grace</string>
          <key>match</key>
          <string>(?:(:(?:=?))|([-|@#!%$?&amp;=:\.\*~+\&lt;/&gt;\\\^]+))\s*(?=\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.grace</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.function.grace</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;![A-z\d'])(is)(?![A-z\d'])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.grace</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=\{|\}|(?&lt;=[A-z\d'"&gt;)])(?&lt;!is)\s+$)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
            <dict>
              <key>name</key>
              <string>support.annotation.grace</string>
              <key>match</key>
              <string>[A-z][A-z\d']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>meta.signature.parameters.grace</string>
          <key>begin</key>
          <string>\(</string>
          <key>end</key>
          <string>\)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#signature_args</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\w)(&lt;)</string>
          <key>end</key>
          <string>(&gt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.generic.grace</string>
            </dict>
          </dict>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.generic.grace</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#comma</string>
            </dict>
            <dict>
              <key>name</key>
              <string>support.type.grace</string>
              <key>match</key>
              <string>[A-z][A-z0-9']*</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_names</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bad_operators</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[A-z][A-z\d']*(?=\s*[,\:\)])</string>
          <key>name</key>
          <string>entity.function.grace</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>uuid</key>
  <string>ca03e751-04ef-4330-9a6b-9b99aae1c419</string>
</dict>
</plist>
